language: php

services:
  - docker

sudo: required

branches:
  only:
  - 7.x-3.x
  - travis_integration

before_script:
  - docker pull statonlab/drupal7

script:
  # Set branch name
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  # Travis does a shallow clone so get all branches from origin
  - git config --replace-all remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
  - git pull origin $BRANCH
  # Test tripal 3 installation
  - docker run -it -d --rm --name tripal3 -v "$(pwd)":/modules/tripal statonlab/drupal7
  - sleep 10
  - docker exec -it tripal3 drush en -y tripal
  # Run PHPUnit tests
  - docker exec -it tripal3 bash -c "cd /modules/tripal && composer install && DRUPAL_ROOT=/var/www/html ./vendor/bin/phpunit"
  # Test Tripal 2 installation
  - git checkout refs/remotes/origin/7.x-2.x
  - docker run -it -d --rm --name tripal2 -v "$(pwd)":/modules/tripal statonlab/drupal7
  - sleep 10
  - docker exec -it tripal2 drush en -y tripal tripal_chado tripal_views
  - docker exec -it tripal2 bash -c 'drush pm-disable tripal_core -y'
  - git checkout $BRANCH
  - docker exec -it tripal2 drush en -y tripal
